<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Inktide.API.TTS.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inktide.API.TTS.Application\Inktide.API.TTS.Application.csproj" />
    <ProjectReference Include="..\Inktide.API.TTS.Domain\Inktide.API.TTS.Domain.csproj" />
    <ProjectReference Include="..\Inktide.API.TTS.Infrastructure\Inktide.API.TTS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
