// <auto-generated />
using System;
using Inktide.API.Marketplace.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inktide.API.Marketplace.Infrastructure.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    partial class MarketplaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inktide.API.Marketplace.Domain.Entities.Connector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("author_name");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("auth_type");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsNative")
                        .HasColumnType("boolean")
                        .HasColumnName("is_native");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("connectors", "marketplace");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AuthorName = "Inktide",
                            AuthType = "oauth",
                            Category = "Chat",
                            Description = "Route guild messages to your AI character in real-time.",
                            IconUrl = "/icons/connectors/discord.svg",
                            IsAvailable = true,
                            IsNative = true,
                            Name = "Discord",
                            ShortDescription = "Route guild messages to your AI character",
                            Slug = "discord",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AuthorName = "Inktide",
                            AuthType = "oauth",
                            Category = "Stream",
                            Description = "Let your character react to live chat and stream events.",
                            IconUrl = "/icons/connectors/twitch.svg",
                            IsAvailable = true,
                            IsNative = true,
                            Name = "Twitch",
                            ShortDescription = "Read and respond to Twitch chat live",
                            Slug = "twitch",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AuthorName = "Inktide",
                            AuthType = "apikey",
                            Category = "Chat",
                            Description = "Connect a Telegram bot to relay chat messages to your AI.",
                            IconUrl = "/icons/connectors/telegram.svg",
                            IsAvailable = true,
                            IsNative = true,
                            Name = "Telegram",
                            ShortDescription = "Telegram bot token — no OAuth needed",
                            Slug = "telegram",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AuthorName = "Inktide",
                            AuthType = "oauth",
                            Category = "Stream",
                            Description = "Connect live stream chat to drive AI responses.",
                            IconUrl = "/icons/connectors/youtube.svg",
                            IsAvailable = false,
                            IsNative = false,
                            Name = "YouTube",
                            ShortDescription = "YouTube Live chat (coming soon)",
                            Slug = "youtube",
                            SortOrder = 4,
                            WebsiteUrl = "https://youtube.com"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AuthorName = "Inktide",
                            AuthType = "webhook",
                            Category = "Stream",
                            Description = "Engage your TikTok live audience with AI replies.",
                            IconUrl = "/icons/connectors/tiktok.svg",
                            IsAvailable = false,
                            IsNative = false,
                            Name = "TikTok",
                            ShortDescription = "TikTok LIVE comments (coming soon)",
                            Slug = "tiktok",
                            SortOrder = 5,
                            WebsiteUrl = "https://developers.tiktok.com"
                        });
                });

            modelBuilder.Entity("Inktide.API.Marketplace.Domain.Entities.ConnectorInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_id");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<Guid>("SoulId")
                        .HasColumnType("uuid")
                        .HasColumnName("soul_id");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("SoulId", "ConnectorId")
                        .IsUnique();

                    b.ToTable("connector_installations", "marketplace");
                });

            modelBuilder.Entity("Inktide.API.Marketplace.Domain.Entities.ConnectorInstallation", b =>
                {
                    b.HasOne("Inktide.API.Marketplace.Domain.Entities.Connector", "Connector")
                        .WithMany("Installations")
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connector");
                });

            modelBuilder.Entity("Inktide.API.Marketplace.Domain.Entities.Connector", b =>
                {
                    b.Navigation("Installations");
                });
#pragma warning restore 612, 618
        }
    }
}
