<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Chimera.API.TTS.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Chimera.API.Core\Chimera.API.Core.csproj" />
    <ProjectReference Include="..\..\Chimera.API.Domain\Chimera.API.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Chimera.API.TTS.Infrastructure" />
  </ItemGroup>

</Project>
