<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Inktide.API.Connector.Twitch</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="TwitchLib.Client" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inktide.API.Connector.Application\Inktide.API.Connector.Application.csproj" />
    <ProjectReference Include="..\..\Inktide.API.Core\Inktide.API.Core.csproj" />
  </ItemGroup>

</Project>
