<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>


    <ItemGroup>
        <ProjectReference Include="..\..\Chimera.API.Memory\Chimera.API.Memory.Domain\Chimera.API.Memory.Domain.csproj" />
    </ItemGroup>

</Project>
