using Microsoft.EntityFrameworkCore.Migrations;

namespace Inktide.API.Core.EfCore;

/// <summary>
/// Creates the MassTransit inbox/outbox tables (<c>InboxState</c>, <c>OutboxMessage</c>,
/// <c>OutboxState</c>) in the default schema, skipping any that already exist.
///
/// Several bounded contexts map these tables to the same unqualified names, so each of their
/// migrations creates them. On a fresh database those migrations run concurrently and only the
/// first plain CREATE TABLE would succeed. The transaction-scoped advisory lock makes the
/// migrations take turns, and IF NOT EXISTS lets every one after the first become a no-op.
/// </summary>
public static class MassTransitOutboxTables
{
    public static void CreateIfMissing(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("SELECT pg_advisory_xact_lock(hashtext('inktide.masstransit.outbox'));");

        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "InboxState" (
                "Id"                 bigint GENERATED BY DEFAULT AS IDENTITY,
                "MessageId"          uuid                     NOT NULL,
                "ConsumerId"         uuid                     NOT NULL,
                "LockId"             uuid                     NOT NULL,
                "RowVersion"         bytea,
                "Received"           timestamp with time zone NOT NULL,
                "ReceiveCount"       integer                  NOT NULL,
                "ExpirationTime"     timestamp with time zone,
                "Consumed"           timestamp with time zone,
                "Delivered"          timestamp with time zone,
                "LastSequenceNumber" bigint,
                CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
                CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
            );

            CREATE TABLE IF NOT EXISTS "OutboxMessage" (
                "SequenceNumber"     bigint GENERATED BY DEFAULT AS IDENTITY,
                "EnqueueTime"        timestamp with time zone,
                "SentTime"           timestamp with time zone NOT NULL,
                "Headers"            text,
                "Properties"         text,
                "InboxMessageId"     uuid,
                "InboxConsumerId"    uuid,
                "OutboxId"           uuid,
                "MessageId"          uuid                     NOT NULL,
                "ContentType"        character varying(256)   NOT NULL,
                "Body"               text                     NOT NULL,
                "ConversationId"     uuid,
                "CorrelationId"      uuid,
                "InitiatorId"        uuid,
                "RequestId"          uuid,
                "SourceAddress"      character varying(256),
                "DestinationAddress" character varying(256),
                "ResponseAddress"    character varying(256),
                "FaultAddress"       character varying(256),
                "ExpirationTime"     timestamp with time zone,
                CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber")
            );

            CREATE TABLE IF NOT EXISTS "OutboxState" (
                "OutboxId"           uuid                     NOT NULL,
                "LockId"             uuid                     NOT NULL,
                "RowVersion"         bytea,
                "Created"            timestamp with time zone NOT NULL,
                "Delivered"          timestamp with time zone,
                "LastSequenceNumber" bigint,
                CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
            );

            CREATE INDEX IF NOT EXISTS "IX_InboxState_Delivered" ON "InboxState" ("Delivered");
            CREATE INDEX IF NOT EXISTS "IX_OutboxMessage_EnqueueTime" ON "OutboxMessage" ("EnqueueTime");
            CREATE INDEX IF NOT EXISTS "IX_OutboxMessage_ExpirationTime" ON "OutboxMessage" ("ExpirationTime");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber"
                ON "OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_OutboxMessage_OutboxId_SequenceNumber"
                ON "OutboxMessage" ("OutboxId", "SequenceNumber");
            CREATE INDEX IF NOT EXISTS "IX_OutboxState_Created" ON "OutboxState" ("Created");
            """);
    }
}
