<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Inktide.API.TTS.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inktide.API.TTS.Application\Inktide.API.TTS.Application.csproj" />
    <ProjectReference Include="..\Inktide.API.TTS.Domain\Inktide.API.TTS.Domain.csproj" />
    <ProjectReference Include="..\..\Inktide.API.Core\Inktide.API.Core.csproj" />
    <ProjectReference Include="..\..\Inktide.API.Domain\Inktide.API.Domain.csproj" />
    <ProjectReference Include="..\..\Inktide.API.Soul\Inktide.API.Soul.Application\Inktide.API.Soul.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Flurl" />
    <PackageReference Include="Google.Cloud.TextToSpeech.V1" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

</Project>
