// <auto-generated />
using System;
using Inktide.API.Developer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inktide.API.Developer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DeveloperDbContext))]
    partial class DeveloperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inktide.API.Developer.Domain.Entities.DeveloperApplication", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("ClientSecretHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("client_secret_hash");
                    b.Property<string>("ConnectorSlug").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("connector_slug");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<string>("IconUrl").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("icon_url");
                    b.Property<string>("KeycloakClientId").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("keycloak_client_id");
                    b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("name");
                    b.Property<string>("OwnerUserId").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("owner_user_id");
                    b.Property<string[]>("RedirectUris").IsRequired().HasColumnType("text[]").HasColumnName("redirect_uris");
                    b.Property<string[]>("Scopes").IsRequired().HasColumnType("text[]").HasColumnName("scopes");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("status");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.Property<string>("WebhookSecretHash").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("webhook_secret_hash");
                    b.Property<string>("WebhookUrl").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("webhook_url");
                    b.HasKey("Id");
                    b.HasIndex("KeycloakClientId").IsUnique();
                    b.HasIndex("OwnerUserId");
                    b.ToTable("applications", "developer");
                });

            modelBuilder.Entity("Inktide.API.Developer.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("ApplicationId").HasColumnType("uuid").HasColumnName("application_id");
                    b.Property<int>("Attempt").HasColumnType("integer").HasColumnName("attempt");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<DateTime?>("DeliveredAt").HasColumnType("timestamp with time zone").HasColumnName("delivered_at");
                    b.Property<string>("EventType").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("event_type");
                    b.Property<DateTime?>("NextRetryAt").HasColumnType("timestamp with time zone").HasColumnName("next_retry_at");
                    b.Property<string>("PayloadJson").IsRequired().HasColumnType("jsonb").HasColumnName("payload_json");
                    b.Property<string>("ResponseBody").HasColumnType("text").HasColumnName("response_body");
                    b.Property<int?>("StatusCode").HasColumnType("integer").HasColumnName("status_code");
                    b.HasKey("Id");
                    b.HasIndex("ApplicationId");
                    b.HasIndex("NextRetryAt");
                    b.ToTable("webhook_deliveries", "developer");
                });

            modelBuilder.Entity("Inktide.API.Developer.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("Inktide.API.Developer.Domain.Entities.DeveloperApplication", "Application")
                        .WithMany("Deliveries")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Application");
                });

            modelBuilder.Entity("Inktide.API.Developer.Domain.Entities.DeveloperApplication", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
