[package]
name = "chimera-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chimera-server"
path = "src/main.rs"

[dependencies]
chimera-lipsync = { path = "../chimera-lipsync" }
chimera-animation = { path = "../chimera-animation" }
chimera-audio = { path = "../chimera-audio" }
chimera-rendering = { path = "../chimera-rendering" }
