<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Inktide.API.Project.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inktide.API.Project\Inktide.API.Project.Domain\Inktide.API.Project.Domain.csproj" />
    <ProjectReference Include="..\Inktide.API.Project\Inktide.API.Project.Application\Inktide.API.Project.Application.csproj" />
    <ProjectReference Include="..\Inktide.API.Project\Inktide.API.Project.Infrastructure\Inktide.API.Project.Infrastructure.csproj" />
    <ProjectReference Include="..\Inktide.API.Project\Inktide.API.Project.REST\Inktide.API.Project.REST.csproj" />
    <ProjectReference Include="..\Inktide.API.Core\Inktide.API.Core.csproj" />
  </ItemGroup>

</Project>
