import type { AiCharacter } from './types'

/** SRP: только дефолтные значения и фабричная функция. */
export const DEFAULTS = {
  systemPrompt:
    'You are a friendly AI companion on a live stream. You interact with chat, react to events, and entertain viewers. Keep responses concise and engaging.',
  responseDelayMs: 1500,
  maxResponseLength: 400,
  autoModerate: true,
  language: 'en',
  typingSimulation: true,
  temperature: 0.7,
  maxTokens: 512,
  topP: 0.9,
  frequencyPenalty: 0,
  presencePenalty: 0,
  memoryEnabled: true,
  maxMemories: 100,
  retentionDays: 30,
  importanceThreshold: 0.5,
  emotionIntensityScale: 1.0,
  autoPilotEnabled: false,
  idleTimeoutSeconds: 120,
  minIntervalSeconds: 60,
  mood: 'neutral',
  llmProviderId: null as string | null,
  llmModelId: null as string | null,
  llmBaseUrl: null as string | null,
  ttsProviderId: null as string | null,
  ttsVoiceId: null as string | null,
  speed: 1.0,
  stability: 0.5,
  similarityBoost: 0.75,
  style: 0.0,
  useSpeakerBoost: true,
  pitch: 1.0,
  volume: 1.0,
} as const

export const createDefaultCharacter = (): Omit<AiCharacter, 'id'> => ({
  name: '',
  slug: '',
  personality: '',
  isActive: false,
  visibility: 'private',
  systemPrompt: DEFAULTS.systemPrompt,
  appearance: {
    avatarUrl: null,
    bannerColorIndex: 0,
    activeSceneId: null,
    modelType: 'none',
    modelFileName: undefined,
    keyPhrases: '',
  },
  llm: {
    providerId: DEFAULTS.llmProviderId,
    modelId: DEFAULTS.llmModelId,
    baseUrl: DEFAULTS.llmBaseUrl,
    temperature: DEFAULTS.temperature,
    maxTokens: DEFAULTS.maxTokens,
    topP: DEFAULTS.topP,
    frequencyPenalty: DEFAULTS.frequencyPenalty,
    presencePenalty: DEFAULTS.presencePenalty,
  },
  tts: {
    providerId: DEFAULTS.ttsProviderId,
    voiceId: DEFAULTS.ttsVoiceId,
    modelId: null,
    apiKey: null,
    baseUrl: null,
    speed: DEFAULTS.speed,
    stability: DEFAULTS.stability,
    similarityBoost: DEFAULTS.similarityBoost,
    style: DEFAULTS.style,
    useSpeakerBoost: DEFAULTS.useSpeakerBoost,
    pitch: DEFAULTS.pitch,
    volume: DEFAULTS.volume,
  },
  behavior: {
    responseDelayMs: DEFAULTS.responseDelayMs,
    maxResponseLength: DEFAULTS.maxResponseLength,
    autoModerate: DEFAULTS.autoModerate,
    language: DEFAULTS.language,
    typingSimulation: DEFAULTS.typingSimulation,
    emotionIntensityScale: DEFAULTS.emotionIntensityScale,
  },
  memory: {
    enabled: DEFAULTS.memoryEnabled,
    maxMemories: DEFAULTS.maxMemories,
    retentionDays: DEFAULTS.retentionDays,
    importanceThreshold: DEFAULTS.importanceThreshold,
  },
  autoPilot: {
    enabled: DEFAULTS.autoPilotEnabled,
    idleTimeoutSeconds: DEFAULTS.idleTimeoutSeconds,
    minIntervalSeconds: DEFAULTS.minIntervalSeconds,
    mood: DEFAULTS.mood,
  },
  channels: [],
})
