// <auto-generated />
using System;
using Inktide.API.Memory.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inktide.API.Memory.Infrastructure.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    [Migration("20260602000034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inktide.API.Memory.Domain.Models.MemoryMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("general")
                        .HasColumnName("category");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FactText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fact_text");

                    b.Property<double>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.5)
                        .HasColumnName("importance");

                    b.Property<DateTime?>("LastRecalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recalled_at");

                    b.Property<string>("QdrantPointId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qdrant_point_id");

                    b.Property<int>("RecallCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("recall_count");

                    b.Property<DateTime>("RememberedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("remembered_at");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("chat")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("idx_memory_card");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_memory_expiry")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("CharacterId", "Category")
                        .HasDatabaseName("idx_memory_category");

                    b.HasIndex("CharacterId", "Importance")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_memory_importance");

                    b.HasIndex("CharacterId", "QdrantPointId")
                        .IsUnique();

                    b.ToTable("memory_metadata", "soul");
                });
#pragma warning restore 612, 618
        }
    }
}
