// Shared Tailwind class strings for brain settings panels

export const infoContent = 'py-2'
export const formGroup = 'mb-7'
export const label = 'block text-body font-semibold font-[var(--font-ui)] text-(--text-primary) mb-2'
export const labelHint = 'text-xs text-(--text-muted) mt-0.5 leading-[1.4]'
export const labelInBlock = 'block text-body-md font-bold text-(--text-primary) mb-1'
export const inputCls = 'w-full py-[0.625rem] px-[0.875rem] bg-[var(--panel-input-bg)] border border-[var(--panel-input-border)] rounded-[6px] text-(--text-primary) font-[var(--font-ui)] text-sm outline-none transition-[border-color,background] duration-[120ms] ease focus:border-white/20 focus:bg-[var(--panel-input-bg-hover)] placeholder:text-[rgba(139,144,154,0.45)]'
export const sliderHeader = 'flex justify-between items-start gap-4 mb-3'
export const sliderValue = 'text-caption font-semibold font-mono text-(--accent-red-bright) bg-[linear-gradient(135deg,rgba(237,62,62,0.15),rgba(237,62,62,0.08))] py-0.5 px-[0.375rem] rounded-[0.25rem] border border-[rgba(237,62,62,0.2)] shrink-0'
export const voiceSelectWrap = 'relative flex items-center mt-2'
export const voiceSelect = 'w-full appearance-none bg-[var(--panel-input-bg)] border border-[var(--panel-input-border)] rounded-[6px] py-[0.625rem] pr-11 pl-[0.875rem] text-(--text-primary) font-[var(--font-ui)] text-body cursor-pointer outline-none transition-[background,border-color] duration-[120ms] ease hover:bg-[var(--panel-input-bg-hover)] hover:border-[var(--panel-input-border-hover)] focus:bg-[var(--panel-input-bg-hover)] focus:border-white/20 [&_option]:bg-[var(--panel-input-bg)]'
export const voiceSelectChevron = 'absolute right-4 text-white/30 pointer-events-none shrink-0'
export const btnTest = 'py-[0.4rem] px-[0.85rem] rounded-[6px] text-[0.8rem] font-medium cursor-pointer bg-[rgba(99,102,241,0.12)] text-[#818cf8] border border-[rgba(99,102,241,0.25)] transition-[background] duration-150 whitespace-nowrap hover:enabled:bg-[rgba(99,102,241,0.22)] disabled:opacity-45 disabled:cursor-default'
export const validationOk = 'py-3 px-4 rounded-[8px] text-sm mb-3 bg-green-500/10 text-green-500'
export const validationFailed = 'py-3 px-4 rounded-[8px] text-sm mb-3 flex flex-col gap-[0.4rem] bg-red-500/10 border border-red-500/25 text-(--text-primary)'
export const btnContinueAnyway = 'self-start mt-1 py-[0.35rem] px-3 rounded-[6px] text-xs font-medium cursor-pointer bg-red-500/15 text-red-500 border border-red-500/30 transition-[background] duration-150 hover:bg-red-500/25'
export const kvRow = 'flex gap-2 items-center mb-[0.375rem]'
export const kvRemoveBtn = 'shrink-0 py-[0.3rem] px-[0.55rem] rounded-[5px] text-xs cursor-pointer bg-transparent text-(--text-muted) border border-(--border) transition-[background,color] duration-150 hover:bg-red-500/10 hover:text-red-500 hover:border-red-500/30'
export const kvAddBtn = 'mt-1 py-[0.3rem] px-[0.65rem] rounded-[6px] text-xs font-medium cursor-pointer bg-transparent text-(--text-muted) border border-dashed border-(--border) transition-[background,color] duration-150 hover:bg-white/[0.05] hover:text-white/60'
