<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Inktide.API.Soul.REST</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Inktide.API.Core\Inktide.API.Core.csproj" />
    <ProjectReference Include="..\Inktide.API.Soul.Application\Inktide.API.Soul.Application.csproj" />
    <ProjectReference Include="..\Inktide.API.Soul.REST.Models\Inktide.API.Soul.REST.Models.csproj" />
  </ItemGroup>

</Project>
