<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Inktide.API.TTS.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inktide.API.TTS.Domain\Inktide.API.TTS.Domain.csproj" />
    <ProjectReference Include="..\..\Inktide.API.Domain\Inktide.API.Domain.csproj" />
  </ItemGroup>

</Project>
