// <auto-generated />
using System;
using System.Net;
using Inktide.API.Soul.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inktide.API.Soul.Infrastructure.Migrations
{
    [DbContext(typeof(SoulDbContext))]
    [Migration("20260326172920_AddAiCardModels")]
    partial class AddAiCardModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Behavior")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("behavior");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DonkeyEngine")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("donkey_engine");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("LlmCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("llm_catalog_id");

                    b.Property<string>("LlmConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("llm_config");

                    b.Property<string>("MemorySettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("memory_settings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("personality");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<Guid?>("TtsCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("tts_catalog_id");

                    b.Property<string>("TtsConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("tts_config");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LlmCatalogId");

                    b.HasIndex("TtsCatalogId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_ai_cards_user_id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("idx_ai_cards_user_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("UserId", "Slug")
                        .IsUnique();

                    b.ToTable("ai_cards", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<string>("BotUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bot_username");

                    b.Property<string>("ChannelId")
                        .HasColumnType("text")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_name");

                    b.Property<DateTime?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OAuthTokenEnc")
                        .HasColumnType("text")
                        .HasColumnName("oauth_token_enc");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("twitch")
                        .HasColumnName("platform");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_ai_card_channels_card");

                    b.HasIndex("Platform", "IsActive")
                        .HasDatabaseName("idx_ai_card_channels_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("AiCardId", "Platform", "ChannelName")
                        .IsUnique();

                    b.ToTable("ai_card_channels", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_url");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_ai_card_models_card");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_card_models_storage_key");

                    b.HasIndex("UserId", "AiCardId")
                        .HasDatabaseName("idx_ai_card_models_user_card");

                    b.ToTable("ai_card_models", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("ToolConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tool_config");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_ai_card_tools_card");

                    b.HasIndex("AiCardId", "ToolName")
                        .IsUnique();

                    b.ToTable("ai_card_tools", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_user");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_audit_entity");

                    b.ToTable("audit_log", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.LlmCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("free")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ModelId")
                        .IsUnique();

                    b.ToTable("llm_catalog", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.MemoryMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("general")
                        .HasColumnName("category");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FactText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fact_text");

                    b.Property<double>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.5)
                        .HasColumnName("importance");

                    b.Property<DateTime?>("LastRecalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recalled_at");

                    b.Property<string>("QdrantPointId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qdrant_point_id");

                    b.Property<int>("RecallCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("recall_count");

                    b.Property<DateTime>("RememberedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("remembered_at");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("chat")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_memory_card");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_memory_expiry")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("AiCardId", "Category")
                        .HasDatabaseName("idx_memory_category");

                    b.HasIndex("AiCardId", "Importance")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_memory_importance");

                    b.HasIndex("AiCardId", "QdrantPointId")
                        .IsUnique();

                    b.ToTable("memory_metadata", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.TtsCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("en")
                        .HasColumnName("language");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("SampleUrl")
                        .HasColumnType("text")
                        .HasColumnName("sample_url");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("free")
                        .HasColumnName("tier");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voice_id");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "VoiceId")
                        .IsUnique();

                    b.ToTable("tts_catalog", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.UsageDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<int>("DonkeyThoughts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("donkey_thoughts");

                    b.Property<int>("LlmCalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("llm_calls");

                    b.Property<int>("MessagesReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("messages_received");

                    b.Property<int>("MessagesSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("messages_sent");

                    b.Property<int>("TokensCompletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tokens_completion");

                    b.Property<int>("TokensPrompt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tokens_prompt");

                    b.Property<int>("TtsCharacters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tts_characters");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date")
                        .HasColumnName("usage_date");

                    b.HasKey("Id");

                    b.HasIndex("UsageDate")
                        .HasDatabaseName("idx_usage_daily_date");

                    b.HasIndex("AiCardId", "UsageDate")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_usage_daily_card_date");

                    b.ToTable("usage_daily", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCard", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.LlmCatalogEntry", "LlmCatalog")
                        .WithMany()
                        .HasForeignKey("LlmCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inktide.API.Soul.Domain.Entities.TtsCatalogEntry", "TtsCatalog")
                        .WithMany()
                        .HasForeignKey("TtsCatalogId");

                    b.Navigation("LlmCatalog");

                    b.Navigation("TtsCatalog");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardChannel", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany("Channels")
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardModel", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany()
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardTool", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany("Tools")
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.MemoryMetadata", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany()
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.UsageDaily", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany()
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCard", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
