// <auto-generated />
using System;
using System.Net;
using Inktide.API.Soul.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inktide.API.Soul.Infrastructure.Migrations
{
    [DbContext(typeof(SoulDbContext))]
    partial class SoulDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Appearance")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("appearance");

                    b.Property<string>("AutoPilot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("auto_pilot");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("LlmCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("llm_catalog_id");

                    b.Property<string>("LlmConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("llm_config");

                    b.Property<string>("MemorySettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("memory_settings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("personality");

                    b.Property<string>("PersonalityConfig")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("personality_config")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("ResponseBehavior")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_behavior");

                    b.Property<string>("ScreenAwarenessSettings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("screen_awareness_settings")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("a0")
                        .HasColumnName("sort_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'[]'");

                    b.Property<Guid?>("TtsCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("tts_catalog_id");

                    b.Property<string>("TtsConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("tts_config");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("private")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_ai_cards_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("LlmCatalogId");

                    b.HasIndex("TtsCatalogId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_ai_cards_user_id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("idx_ai_cards_user_active")
                        .HasFilter("is_active = true AND deleted_at IS NULL");

                    b.HasIndex("UserId", "Slug")
                        .IsUnique();

                    b.HasIndex("UserId", "SortKey")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_cards_sort")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("ai_cards", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<string>("BotUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bot_username");

                    b.Property<string>("ChannelId")
                        .HasColumnType("text")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_name");

                    b.Property<DateTime?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomBotTokenEnc")
                        .HasColumnType("text")
                        .HasColumnName("custom_bot_token_enc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OAuthTokenEnc")
                        .HasColumnType("text")
                        .HasColumnName("oauth_token_enc");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("twitch")
                        .HasColumnName("platform");

                    b.Property<string>("RefreshTokenEnc")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_enc");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_ai_card_channels_card");

                    b.HasIndex("Platform", "IsActive")
                        .HasDatabaseName("idx_ai_card_channels_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("AiCardId", "Platform", "ChannelName")
                        .IsUnique();

                    b.ToTable("ai_card_channels", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardCustomSceneTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<string>("LabelNormalized")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label_normalized");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_ai_card_custom_scene_tags_card");

                    b.HasIndex("AiCardId", "LabelNormalized")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_card_custom_scene_tags_card_label_norm");

                    b.ToTable("ai_card_custom_scene_tags", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_url");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_ai_card_models_card");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_card_models_storage_key");

                    b.HasIndex("AiCardId", "IsActive")
                        .HasDatabaseName("idx_ai_card_models_active");

                    b.HasIndex("UserId", "AiCardId")
                        .HasDatabaseName("idx_ai_card_models_user_card");

                    b.ToTable("ai_card_models", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardRunPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OverrideEmotionPresetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("override_emotion_preset_id");

                    b.Property<string>("OverrideLlmModelId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("override_llm_model_id");

                    b.Property<float?>("OverrideTemperature")
                        .HasColumnType("real")
                        .HasColumnName("override_temperature");

                    b.Property<string>("OverrideVoiceProfileId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("override_voice_profile_id");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("a0")
                        .HasColumnName("sort_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_ai_card_run_presets_card");

                    b.HasIndex("AiCardId", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_card_run_presets_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("AiCardId", "SortKey")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_card_run_presets_sort");

                    b.HasIndex("UserId", "AiCardId")
                        .HasDatabaseName("idx_ai_card_run_presets_user_card");

                    b.ToTable("ai_card_run_presets", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardScene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_url");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("a0")
                        .HasColumnName("sort_key");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("Tag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tag");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_ai_card_scenes_card");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_card_scenes_storage_key");

                    b.HasIndex("AiCardId", "SortKey")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_card_scenes_sort");

                    b.HasIndex("UserId", "AiCardId")
                        .HasDatabaseName("idx_ai_card_scenes_user_card");

                    b.ToTable("ai_card_scenes", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("ToolConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tool_config");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("AiCardId")
                        .HasDatabaseName("idx_ai_card_tools_card");

                    b.HasIndex("AiCardId", "ToolName")
                        .IsUnique();

                    b.ToTable("ai_card_tools", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_user");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_audit_entity");

                    b.ToTable("audit_log", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.LlmCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<bool>("RequiresApiKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("requires_api_key");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("free")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ModelId")
                        .IsUnique();

                    b.ToTable("llm_catalog", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_outbox_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_events", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.TtsCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("en")
                        .HasColumnName("language");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<bool>("RequiresApiKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("requires_api_key");

                    b.Property<string>("SampleUrl")
                        .HasColumnType("text")
                        .HasColumnName("sample_url");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("free")
                        .HasColumnName("tier");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voice_id");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "VoiceId")
                        .IsUnique();

                    b.ToTable("tts_catalog", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.UsageDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_card_id");

                    b.Property<int>("DonkeyThoughts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("donkey_thoughts");

                    b.Property<int>("LlmCalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("llm_calls");

                    b.Property<int>("MessagesReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("messages_received");

                    b.Property<int>("MessagesSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("messages_sent");

                    b.Property<int>("TokensCompletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tokens_completion");

                    b.Property<int>("TokensPrompt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tokens_prompt");

                    b.Property<int>("TtsCharacters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tts_characters");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date")
                        .HasColumnName("usage_date");

                    b.Property<int>("VisionEventsDetected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vision_events_detected");

                    b.Property<int>("VisionFramesProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vision_frames_processed");

                    b.HasKey("Id");

                    b.HasIndex("UsageDate")
                        .HasDatabaseName("idx_usage_daily_date");

                    b.HasIndex("AiCardId", "UsageDate")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_usage_daily_card_date");

                    b.ToTable("usage_daily", "soul");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.UserProviderCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyEnc")
                        .HasColumnType("text")
                        .HasColumnName("api_key_enc");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("Config")
                        .HasColumnType("text")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_provider_credentials_user");

                    b.HasIndex("UserId", "ProviderId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_provider_credentials_user_provider");

                    b.ToTable("user_provider_credentials", "soul");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCard", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.LlmCatalogEntry", "LlmCatalog")
                        .WithMany()
                        .HasForeignKey("LlmCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inktide.API.Soul.Domain.Entities.TtsCatalogEntry", "TtsCatalog")
                        .WithMany()
                        .HasForeignKey("TtsCatalogId");

                    b.Navigation("LlmCatalog");

                    b.Navigation("TtsCatalog");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardChannel", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany("Channels")
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardCustomSceneTag", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany()
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardModel", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany()
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardRunPreset", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany()
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardScene", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany()
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCardTool", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany("Tools")
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.UsageDaily", b =>
                {
                    b.HasOne("Inktide.API.Soul.Domain.Entities.AiCard", "AiCard")
                        .WithMany()
                        .HasForeignKey("AiCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiCard");
                });

            modelBuilder.Entity("Inktide.API.Soul.Domain.Entities.AiCard", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
