<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Inktide.API.Soul.Grpc</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="DryIoc.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Inktide.API.Core\Inktide.API.Core.csproj" />
    <ProjectReference Include="..\Inktide.API.Soul.Application\Inktide.API.Soul.Application.csproj" />
  </ItemGroup>

</Project>
