syntax = "proto3";

option csharp_namespace = "Chimera.ApiGateway.Grpc.Contracts.Auth";

package chimera.auth;

service AuthService {
  rpc Register  (RegisterRequest) returns (AuthResponse);
  rpc Login  (LoginRequest) returns (AuthResponse);
  rpc Refresh (RefreshRequest) returns (AuthResponse);
  rpc Logout (LogoutRequest) returns (LogoutResponse);
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string display_name = 3;
}

message LoginRequest {
  optional string api_key = 1;
  optional string email_or_username = 2;
  optional string password  = 3;
}

message RefreshRequest {
  string refresh_token = 1;
}

message LogoutRequest {
  string refresh_token = 1;
}

message AuthResponse {
  string access_token = 1;
  string token_type = 2;
  int32  expires_in = 3;
  string refresh_token = 4;
  int32  refresh_expires_in = 5;
}

message LogoutResponse {
  bool success = 1;
}
